services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/react-app
      - /react-app/node_modules
    ports:
      - '5173:5173'
    command: npm run dev
  # backend:
  #   build: ./backend
  #   container_name: backend_c
  #   ports:
  #     - '4000:4000'
  #   stdin_open: true
  #   tty: true