services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./frontend:/react-app
      - /react-app/node_modules
    ports:
      - '5173:5173'
    command: npm run dev
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    command: npm run start:dev